"""
Type stubs for Transaction model
"""
from typing import Any, ClassVar, Iterator, TypeVar, Generic
from datetime import datetime

T = TypeVar("T")


class QuerySet(Generic[T], Iterator[T]):
    """Stub for mongoengine QuerySet"""
    def first(self) -> T | None: ...
    def all(self) -> "QuerySet[T]": ...
    def count(self) -> int: ...
    def filter(self, **kwargs: Any) -> "QuerySet[T]": ...
    def order_by(self, *keys: str) -> "QuerySet[T]": ...
    def limit(self, n: int) -> "QuerySet[T]": ...
    def skip(self, n: int) -> "QuerySet[T]": ...
    def __call__(self, **kwargs: Any) -> "QuerySet[T]": ...
    def __iter__(self) -> Iterator[T]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> T: ...

class Transaction:
    """Cart document model"""
    # MongoDB injected fields
    id: Any
    pk: Any

    cart_id :str
    transaction_value :float
    currency = str
    created_at :datetime
    updated_at:datetime
    status :str
    # Class-level attributes injected by mongoengine
    objects: ClassVar[QuerySet["Transaction"]]

    def __init__(
        self,
        cart_id: str = ...,
        status: str = ...,
        currency: str = ...,
        created_at: datetime | None = ...,
        updated_at: datetime | None = ...,
        transaction_value: float | None = ...,
    ) -> None: ...

    def get_total(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...
    def save(self, *args: Any, **kwargs: Any) -> "Transaction": ...
    def delete(self, *args: Any, **kwargs: Any) -> None: ...
    def reload(self) -> "Transaction": ...
    def to_mongo(self) -> dict[str, Any]: ...
    def validate(self) -> None: ...
    def clean(self) -> None: ...
